### ISSUE TITLE
PR previews should use test database

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRefOnline#1335]
Currently, the azure pr preview uses the production app settings, in particular the main database.
Changing this requires one of the following to be fixed:
- https://github.com/Azure/static-web-apps/issues/86
- https://github.com/Azure/azure-cli/issues/22552 
- https://github.com/Azure/static-web-apps/issues/677

Using
```
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Update app settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az staticwebapp appsettings set --name jabref-online --setting-names "DATABASE_URL=$DATABASE_URL"
        env:
          DATABASE_URL: ${{ secrets.AZURE_TEST_DATABASE_URL }}
```

Alternative: #1343
